apiVersion: v1
kind: Pod
metadata:
  name: rampod
spec:
  terminationGracePeriodSeconds: 1
  containers:
  - name: shell
    image: alpine
    command: ["sleep", "3600"]
    volumeMounts:
    - mountPath: /cache
      name: cache
    resources:
      limits:
        memory: 10Mi
      requests:
        cpu: 5m
        memory: 10Mi
  volumes:
  - name: cache
    csi:
      driver: ramdisk.csi.storage.gke.io

