name: Presubmit Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 1.23 # Keep in sync with ./go.mod
    - name: verify
      run: ./hack/verify-all.sh
    - name: unittest
      run: go test -v ./pkg/...
